__author__ = 'broy'

import smtplib, os
from email.MIMEMultipart import MIMEMultipart
from email.MIMEBase import MIMEBase
from email.MIMEText import MIMEText
from email.Utils import COMMASPACE, formatdate
from email import Encoders


# copied from
# http://git.dev.dw.sc.gwallet.com/projects/DW/repos/r1-dw-dt-app/browse/data_triggers/util_email.py


def send_email(recipients,subject,body,attachments = []):
   msg = MIMEMultipart()
   msg['Subject'] = 'R1 Autogenerated Email: ' + subject
   msg['From'] = 'dtops@radiumone.com'
   msg['To'] = ", ".join(recipients)
   msg.attach( MIMEText(body, 'html') )

   for f in attachments:
      part = MIMEBase('application', "octet-stream")
      part.set_payload( open(f,"rb").read() )
      Encoders.encode_base64(part)
      part.add_header('Content-Disposition', 'attachment; filename="%s"' % os.path.basename(f))
      msg.attach(part)

   # The actual mail send
   server = smtplib.SMTP("localhost")

   server.sendmail('dtops@radiumone.com', recipients, msg.as_string())
   server.quit()


if __name__ == "__main__":
   recipients = []
   recipients.append("broy@radiumone.com")
   # recipients.append(row[1])
   subject = "Programmable Bidder : bid list updated with domains and multipliers"
   line_id = 37237
   strategy_id = 640606
   bid_list_id = 106
   body = "Programmable Bidder invoked (if uniques criteria was satisfied).<br>"
   body += """These are the links to the<br>
              <a href="https://rui.gwallet.com/us/line/details/{}">line</a>,<br>
              <a href="https://rui.gwallet.com/us/strategy/details/{}">strategy</a> and<br>
              <a href="https://rui.gwallet.com/us/management/bidmultipliers/managebidmultiplierslist/{}">bid list</a><br> respectively""".format(line_id, strategy_id, bid_list_id)
   send_email(recipients, subject, body, "")