import smtplib, os
from email.MIMEMultipart import MIMEMultipart
from email.MIMEBase import MIMEBase
from email.MIMEText import MIMEText
from email.Utils import COMMASPACE, formatdate
from email import Encoders


# copied from
# http://git.dev.dw.sc.gwallet.com/projects/DW/repos/r1-dw-dt-app/browse/data_triggers/util_email.py


def send_email(recipients,subject,body,attachments = []):
   #Configure the email
   msg = MIMEMultipart()
   msg['Subject'] = 'R1 Autogenerated Email: ' + subject
   msg['From'] = 'dtops@radiumone.com'
   msg['To'] = ", ".join(recipients)
   msg.attach( MIMEText(body, 'html') )

   for f in attachments:
      part = MIMEBase('application', "octet-stream")
      part.set_payload( open(f,"rb").read() )
      Encoders.encode_base64(part)
      part.add_header('Content-Disposition', 'attachment; filename="%s"' % os.path.basename(f))
      msg.attach(part)

   # The actual mail send 
   server = smtplib.SMTP("localhost") 
       
   server.sendmail('dtops@radiumone.com', recipients, msg.as_string())  
   server.quit()

#send_email(['dtops@radiumone.com'],"Alert","testing one two three")